jwt: {
  access_token_expiry_hour: 2,
  refresh_token_expiry_hour: 168,
  access_token_secret: "access_token_secret",
  refresh_token_secret: "refresh_token_secret"
}

google: {
  client_id: "524616912419-pn9vslg9rik6e7skd25ci3cegdqfl4qc.apps.googleusercontent.com",
  client_secret: "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",
  auth_uri: "https://accounts.google.com/o/oauth2/auth",
  token_uri: "https://oauth2.googleapis.com/token",
  redirect_uri: "http://localhost:5000/callback/google"
}

kakao: {

}

